version: '3.11'

services:
  routes:
    build:
      context: ./routes
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    networks:
      - mynetwork
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.4-jammy
    restart: always
    container_name: userms_db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
