version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    networks:
      - mynetwork

  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
