# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x1e\n\x0eGetUserRequest\x12\x0c\n\x04\x63nic\x18\x01 \x01(\x03\"t\n\x0fGetUserResponse\x12\x0c\n\x04\x63nic\x18\x01 \x01(\x03\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"t\n\x0fPostUserRequest\x12\x0c\n\x04\x63nic\x18\x01 \x01(\x03\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"#\n\x10PostUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"s\n\x0ePutUserRequest\x12\x0c\n\x04\x63nic\x18\x01 \x01(\x03\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\"\n\x0fPutUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x11\x44\x65leteUserRequest\x12\x0c\n\x04\x63nic\x18\x01 \x01(\x03\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xdd\x01\n\x0bUserService\x12/\n\nGetUserRPC\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\x12\x32\n\x0bPostUserRPC\x12\x10.PostUserRequest\x1a\x11.PostUserResponse\x12/\n\nPutUserRPC\x12\x0f.PutUserRequest\x1a\x10.PutUserResponse\x12\x38\n\rDeleteUserRPC\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_GETUSERREQUEST']._serialized_start = 14
    _globals['_GETUSERREQUEST']._serialized_end = 44
    _globals['_GETUSERRESPONSE']._serialized_start = 46
    _globals['_GETUSERRESPONSE']._serialized_end = 162
    _globals['_POSTUSERREQUEST']._serialized_start = 164
    _globals['_POSTUSERREQUEST']._serialized_end = 280
    _globals['_POSTUSERRESPONSE']._serialized_start = 282
    _globals['_POSTUSERRESPONSE']._serialized_end = 317
    _globals['_PUTUSERREQUEST']._serialized_start = 319
    _globals['_PUTUSERREQUEST']._serialized_end = 434
    _globals['_PUTUSERRESPONSE']._serialized_start = 436
    _globals['_PUTUSERRESPONSE']._serialized_end = 470
    _globals['_DELETEUSERREQUEST']._serialized_start = 472
    _globals['_DELETEUSERREQUEST']._serialized_end = 505
    _globals['_DELETEUSERRESPONSE']._serialized_start = 507
    _globals['_DELETEUSERRESPONSE']._serialized_end = 544
    _globals['_USERSERVICE']._serialized_start = 547
    _globals['_USERSERVICE']._serialized_end = 768
# @@protoc_insertion_point(module_scope)
